USE IMT577_DW_ANUSHISETH_MODULE5

/*
  VIEW 1: ACTUAL SALE VS TARGET SALE
*/
DROP VIEW YEARLY_STORE_SALES_TARGET_COMP;

-- CREATE VIEW YEARLY_STORE_SALES_TARGET_COMP
CREATE OR REPLACE SECURE VIEW YEARLY_STORE_SALES_TARGET_COMP
AS
SELECT c.DIMSTOREID,DIM_STORE.STORENUMBER,c.YEAR,c.SALESAMOUNT,c.SALESTARGETAMOUNT
FROM (
  SELECT a.DIMSTOREID, a.YEAR, b.SALESAMOUNT, a.SALESTARGETAMOUNT
  FROM (
    SELECT DIMSTOREID,  LEFT(CAST(DIMTARGETDATEID AS varchar(8)),4) as YEAR, SALESTARGETAMOUNT
    FROM FACT_SRCSALESTARGET
    WHERE DIMSTOREID <> 1
  ) a
  INNER JOIN (
    SELECT DIMSTOREID, SUM(SALEAMOUNT) as SALESAMOUNT, YEAR
    FROM (
      SELECT DIMSTOREID, DIMSALEDATEID, SALEAMOUNT, LEFT(CAST(DIMSALEDATEID AS varchar(8)),4) as YEAR
      FROM FACT_SALESACTUAL
    ) TBL_ACTUAL_SALES
    GROUP BY YEAR, DIMSTOREID
  ) b
  ON a.DIMSTOREID= b.DIMSTOREID
  AND a.YEAR = b.YEAR
) c 
INNER JOIN DIM_STORE
ON c.DIMSTOREID = DIM_STORE.DIMSTOREID;


------- TEST QUERY FOR STORE 10 AND 21 -----------

SELECT DIMSTOREID,STORENUMBER,YEAR,SALESAMOUNT,SALESTARGETAMOUNT
FROM YEARLY_STORE_SALES_TARGET_COMP 
WHERE STORENUMBER IN (10,21);


/*
  VIEW 2: ACTUAL SALE VS TARGET SALE
*/

DROP VIEW WEEKLY_STORE_SALES;

-- CREATE VIEW WEEKLY_STORE_SALES
CREATE OR REPLACE SECURE VIEW WEEKLY_STORE_SALES 
AS
SELECT a.DIMSTOREID, MIN(STORENUMBER) as STORENUMBER, SUM(SALEAMOUNT) AS TOTAL_SALES, DAY_NAME, MIN(DAY_NUM_IN_WEEK) as DAY_NUM_IN_WEEK
FROM FACT_SALESACTUAL a
INNER JOIN DIM_DATE b
INNER JOIN DIM_STORE c
ON a.DIMSALEDATEID = b.DATE_PKEY
AND a.DIMSTOREID = c.DIMSTOREID
WHERE a.DIMSTOREID <> 1
GROUP BY DAY_NAME,a.DIMSTOREID;

------- TEST QUERY FOR STORE 10 AND 21 -----------

SELECT DIMSTOREID,STORENUMBER,TOTAL_SALES,DAY_NAME,DAY_NUM_IN_WEEK 
FROM WEEKLY_STORE_SALES 
WHERE STORENUMBER IN (10,21);



/*
  VIEW 3: STORE BY LOCATION (CITY)
*/

DROP VIEW YEARLY_CITY_STORE_SALES;

-- CREATE VIEW YEARLY_CITY_STORE_SALES
CREATE OR REPLACE SECURE VIEW YEARLY_CITY_STORE_SALES 
AS
SELECT CITY, COUNT(DISTINCT DIMSTOREID) as STORECOUNT, SUM(SALEAMOUNT) as SALESAMOUNT, YEAR
FROM (
  SELECT DIMSTOREID, SALEAMOUNT, LEFT(CAST(DIMSALEDATEID AS varchar(8)),4) as YEAR, FACT_SALESACTUAL.DIMLOCATIONID, CITY, STATEPROVINCE, COUNTRY
  FROM FACT_SALESACTUAL
  INNER JOIN DIM_LOCATION
  ON FACT_SALESACTUAL.DIMLOCATIONID =DIM_LOCATION.DIMLOCATIONID
  WHERE FACT_SALESACTUAL.DIMSTOREID <> 1
) TBL_ACTUAL_SALES_LOC
GROUP BY CITY, YEAR;

------- TEST QUERY FOR VIEW 3 -----------

SELECT CITY,STORECOUNT,SALESAMOUNT,YEAR 
FROM YEARLY_CITY_STORE_SALES;



/*
  VIEW 4: STORE BY LOCATION (STATE)
*/

DROP VIEW YEARLY_STATE_STORE_SALES;

-- CREATE VIEW YEARLY_STATE_STORE_SALES
CREATE OR REPLACE SECURE VIEW YEARLY_STATE_STORE_SALES 
AS
SELECT STATEPROVINCE, COUNT(DISTINCT DIMSTOREID) as STORECOUNT, SUM(SALEAMOUNT) as SALESAMOUNT, YEAR
FROM (
  SELECT DIMSTOREID, SALEAMOUNT, LEFT(CAST(DIMSALEDATEID AS varchar(8)),4) as YEAR, FACT_SALESACTUAL.DIMLOCATIONID, CITY, STATEPROVINCE, COUNTRY
  FROM FACT_SALESACTUAL
  INNER JOIN DIM_LOCATION
  ON FACT_SALESACTUAL.DIMLOCATIONID =DIM_LOCATION.DIMLOCATIONID
  WHERE FACT_SALESACTUAL.DIMSTOREID <> 1
) TBL_ACTUAL_SALES_LOC
GROUP BY STATEPROVINCE, YEAR;

------- TEST QUERY FOR VIEW 4 -----------

SELECT STATEPROVINCE,STORECOUNT,SALESAMOUNT,YEAR
FROM YEARLY_STATE_STORE_SALES;


/*
  VIEW 5: SALES BY CHANNEL
*/

DROP VIEW YEARLY_CHANNEL_SALES;

-- CREATE VIEW YEARLY_CHANNEL_SALES
CREATE OR REPLACE SECURE VIEW YEARLY_CHANNEL_SALES 
AS
SELECT CHANNELNAME, MAX(CHANNELCATEGORY) as CHANNELCATEGORY, SUM(SALEAMOUNT) as SALESAMOUNT, YEAR
FROM (
  SELECT DIMSTOREID, SALEAMOUNT, LEFT(CAST(DIMSALEDATEID AS varchar(8)),4) as YEAR, FACT_SALESACTUAL.DIMCHANNELID, CHANNELNAME, CHANNELCATEGORY
  FROM FACT_SALESACTUAL
  INNER JOIN DIM_CHANNEL
  ON FACT_SALESACTUAL.DIMCHANNELID =DIM_CHANNEL.DIMCHANNELID
) TBL_ACTUAL_SALES_CHNL
GROUP BY CHANNELNAME, YEAR;

------- TEST QUERY FOR VIEW 5 -----------

SELECT CHANNELCATEGORY, SUM(SALESAMOUNT), YEAR
FROM YEARLY_CHANNEL_SALES
GROUP BY CHANNELCATEGORY, YEAR;
